### ISSUE TITLE
Inventory of all EBS Disks Types

### ISSUE THREAD

**Issue by ampnh603** [razguru/automation#1]
Greetings, would be interested to see if you could augment this script to pull a list of all EBS disk types to better understand your fleet vs just looking for GP2 based disks?

**Comment by razguru** [comment]
Sure, I was actually catering specific cost-saving use case by gp2-to-gp3 modification but yes I can update the script's   discover parameter/function to prepare lists for all EBS volume types like -
<region_name> _gp2_vol_id
<region_name> _gp3_vol_id
<region_name> _io1_vol_id
<region_name> _io2_vol_id

Is this what you are looking for ?

**Comment by razguru** [comment]
Hi, 
I have updated the script to discover all  EBS volumes types,  present the volume counts on screen and prepare distinct volume_id list.

[ec2-user@ip-172-16-1-92 ~]$ bash gp2_gp3_migration.sh --region us-east-1 discover no-snapshot
 -- Discovered ....( 1 ).... GP2 volumes in us-east-1 || GP2 volume-ids list : _us-east-1_2023-11-10-06:24:50_gp2_vol_id.txt

 -- Discovered ....( 10 ).... GP3 volumes in us-east-1 || GP3 volume-ids list : _us-east-1_2023-11-10-06:24:50_gp3_vol_id.txt

 -- Discovered ....( 1 ).... io1 volumes in us-east-1 || io1 volume-ids list : _us-east-1_2023-11-10-06:24:50_io1_vol_id.txt

 -- Discovered ....( 2 ).... io2 volumes in us-east-1 || io2 volume-ids list : _us-east-1_2023-11-10-06:24:50_io2_vol_id.txt
